In [7]:
import pandas as pd
import numpy as np

# pandas tasks

In [8]:
data=pd.read_csv('weatherAUS.csv')

In [5]:
print(data.head(2))

NameError: name 'data' is not defined

In [6]:
data.drop('Sunshine', inplace=True, axis=1)

NameError: name 'data' is not defined

In [5]:
print(data.head(2))

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation WindGustDir  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN           W   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN         WNW   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0           44.0          W        WNW  ...         71.0         22.0   
1           44.0        NNW        WSW  ...         44.0         25.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   

   RainTomorrow  
0            No  
1            No  

[2 rows x 22 columns]


In [10]:
data['Date_Location'] = data.Date + ' ' + data.Location

In [11]:
print(data.head(2))

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation WindGustDir  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN           W   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN         WNW   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity3pm  Pressure9am  \
0           44.0          W        WNW  ...         22.0       1007.7   
1           44.0        NNW        WSW  ...         25.0       1010.6   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  \
0       1007.1       8.0       NaN     16.9     21.8         No            No   
1       1007.8       NaN       NaN     17.2     24.3         No            No   

       Date_Location  
0  2008-12-01 Albury  
1  2008-12-02 Albury  

[2 rows x 23 columns]


In [20]:
data.dropna()

Date   Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    2009-01-01      Cobar     17.9     35.2       0.0         12.0   
6050    2009-01-02      Cobar     18.4     28.9       0.0         14.8   
6052    2009-01-04      Cobar     19.4     37.6       0.0         10.8   
6053    2009-01-05      Cobar     21.9     38.4       0.0         11.4   
6054    2009-01-06      Cobar     24.2     41.0       0.0         11.2   
...            ...        ...      ...      ...       ...          ...   
143181  2015-07-26  Katherine     18.2     35.5       0.0          5.0   
143182  2015-07-27  Katherine     22.6     33.6       0.0          8.0   
143183  2015-07-28  Katherine     17.4     30.7       0.0         10.8   
143185  2015-07-30  Katherine     13.3     32.0       0.0          5.8   
143186  2015-07-31  Katherine     13.0     32.0       0.0          6.6   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity3pm  \
6049           SSW           48.0        ENE         SW  ...         13.0   
6050             S           37.0        SSE        SSE  ...          8.0   
6052           NNE           46.0        NNE        NNW  ...         22.0   
6053           WNW           31.0        WNW        WSW  ...         22.0   
6054           WNW           35.0         NW        WNW  ...         15.0   
...            ...            ...        ...        ...  ...          ...   
143181         ESE           41.0          S          E  ...         27.0   
143182          SE           46.0         SE        ESE  ...         40.0   
143183         SSE           46.0         SE         SE  ...         42.0   
143185           E           43.0         SE        ESE  ...         28.0   
143186         ENE           43.0         SE          E  ...         32.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049         1006.3       1004.4       2.0       5.0     26.6     33.4   
6050         1012.9       1012.1       1.0       1.0     20.3     27.0   
6052         1012.3       1009.2       1.0       6.0     28.7     34.9   
6053         1012.7       1009.1       1.0       5.0     29.1     35.6   
6054         1010.7       1007.4       1.0       6.0     33.6     37.6   
...             ...          ...       ...       ...      ...      ...   
143181       1018.4       1014.0       0.0       1.0     25.2     34.9   
143182       1020.1       1015.8       6.0       6.0     26.2     33.0   
143183       1021.2       1016.5       0.0       0.0     21.3     30.0   
143185       1019.2       1015.0       0.0       1.0     22.1     31.0   
143186       1017.8       1013.0       0.0       1.0     21.7     31.0   

        RainToday  RainTomorrow         Date_Location  
6049           No            No      2009-01-01 Cobar  
6050           No            No      2009-01-02 Cobar  
6052           No            No      2009-01-04 Cobar  
6053           No            No      2009-01-05 Cobar  
6054           No            No      2009-01-06 Cobar  
...           ...           ...                   ...  
143181         No            No  2015-07-26 Katherine  
143182         No            No  2015-07-27 Katherine  
143183         No            No  2015-07-28 Katherine  
143185         No            No  2015-07-30 Katherine  
143186         No            No  2015-07-31 Katherine  

[61981 rows x 23 columns]

In [21]:
data.dropna(axis=0)

Date   Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    2009-01-01      Cobar     17.9     35.2       0.0         12.0   
6050    2009-01-02      Cobar     18.4     28.9       0.0         14.8   
6052    2009-01-04      Cobar     19.4     37.6       0.0         10.8   
6053    2009-01-05      Cobar     21.9     38.4       0.0         11.4   
6054    2009-01-06      Cobar     24.2     41.0       0.0         11.2   
...            ...        ...      ...      ...       ...          ...   
143181  2015-07-26  Katherine     18.2     35.5       0.0          5.0   
143182  2015-07-27  Katherine     22.6     33.6       0.0          8.0   
143183  2015-07-28  Katherine     17.4     30.7       0.0         10.8   
143185  2015-07-30  Katherine     13.3     32.0       0.0          5.8   
143186  2015-07-31  Katherine     13.0     32.0       0.0          6.6   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity3pm  \
6049           SSW           48.0        ENE         SW  ...         13.0   
6050             S           37.0        SSE        SSE  ...          8.0   
6052           NNE           46.0        NNE        NNW  ...         22.0   
6053           WNW           31.0        WNW        WSW  ...         22.0   
6054           WNW           35.0         NW        WNW  ...         15.0   
...            ...            ...        ...        ...  ...          ...   
143181         ESE           41.0          S          E  ...         27.0   
143182          SE           46.0         SE        ESE  ...         40.0   
143183         SSE           46.0         SE         SE  ...         42.0   
143185           E           43.0         SE        ESE  ...         28.0   
143186         ENE           43.0         SE          E  ...         32.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049         1006.3       1004.4       2.0       5.0     26.6     33.4   
6050         1012.9       1012.1       1.0       1.0     20.3     27.0   
6052         1012.3       1009.2       1.0       6.0     28.7     34.9   
6053         1012.7       1009.1       1.0       5.0     29.1     35.6   
6054         1010.7       1007.4       1.0       6.0     33.6     37.6   
...             ...          ...       ...       ...      ...      ...   
143181       1018.4       1014.0       0.0       1.0     25.2     34.9   
143182       1020.1       1015.8       6.0       6.0     26.2     33.0   
143183       1021.2       1016.5       0.0       0.0     21.3     30.0   
143185       1019.2       1015.0       0.0       1.0     22.1     31.0   
143186       1017.8       1013.0       0.0       1.0     21.7     31.0   

        RainToday  RainTomorrow         Date_Location  
6049           No            No      2009-01-01 Cobar  
6050           No            No      2009-01-02 Cobar  
6052           No            No      2009-01-04 Cobar  
6053           No            No      2009-01-05 Cobar  
6054           No            No      2009-01-06 Cobar  
...           ...           ...                   ...  
143181         No            No  2015-07-26 Katherine  
143182         No            No  2015-07-27 Katherine  
143183         No            No  2015-07-28 Katherine  
143185         No            No  2015-07-30 Katherine  
143186         No            No  2015-07-31 Katherine  

[61981 rows x 23 columns]

In [19]:
print(data)

              Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

       WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity3pm  \
0                W           44.0          W        WNW  .

In [23]:
data.columns=list("ABCDEFGHIJKLMNOPQRSTUVW")

In [25]:
print(data.head(1))

            A       B     C     D    E   F  G     H  I    J  ...     N  \
0  2008-12-01  Albury  13.4  22.9  0.6 NaN  W  44.0  W  WNW  ...  22.0   

        O       P    Q   R     S     T   U   V                  W  
0  1007.7  1007.1  8.0 NaN  16.9  21.8  No  No  2008-12-01 Albury  

[1 rows x 23 columns]


In [26]:
#create datafram
Temperature={
    "location":['peshawar','haripur','islamabad','karachi','mardan'],
    "max_temp":[76,64,60,74,72],
    "min_temp":[10,9,8,9,7]
}

In [27]:
temp_df=pd.DataFrame(Temperature)

In [28]:
temp_df

location  max_temp  min_temp
0   peshawar        76        10
1    haripur        64         9
2  islamabad        60         8
3    karachi        74         9
4     mardan        72         7

In [35]:
grouped_temp_df=temp_df.groupby("location").mean()

In [36]:
grouped_temp_df

max_temp  min_temp
location                     
haripur        64.0       9.0
islamabad      60.0       8.0
karachi        74.0       9.0
mardan         72.0       7.0
peshawar       76.0      10.0

# numpy tasks

In [37]:
#create array 1D
array=np.arange(64)

In [38]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [39]:
array=array.reshape(4,4,4)

In [40]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [44]:
array=array.astype('float64')

In [45]:
array

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]],

       [[32., 33., 34., 35.],
        [36., 37., 38., 39.],
        [40., 41., 42., 43.],
        [44., 45., 46., 47.]],

       [[48., 49., 50., 51.],
        [52., 53., 54., 55.],
        [56., 57., 58., 59.],
        [60., 61., 62., 63.]]])

In [47]:
type(array)

numpy.ndarray

In [48]:
linespace=np.linspace(8,10,28)

In [49]:
linespace

array([ 8.        ,  8.07407407,  8.14814815,  8.22222222,  8.2962963 ,
        8.37037037,  8.44444444,  8.51851852,  8.59259259,  8.66666667,
        8.74074074,  8.81481481,  8.88888889,  8.96296296,  9.03703704,
        9.11111111,  9.18518519,  9.25925926,  9.33333333,  9.40740741,
        9.48148148,  9.55555556,  9.62962963,  9.7037037 ,  9.77777778,
        9.85185185,  9.92592593, 10.        ])

In [52]:
random_array= np.random.rand(1,100)

In [53]:
random_array

array([[0.55406392, 0.68406769, 0.29962583, 0.71825702, 0.37187713,
        0.34125737, 0.71833358, 0.4503873 , 0.36611255, 0.63952876,
        0.09399888, 0.41070301, 0.01465021, 0.95206595, 0.28506331,
        0.16347627, 0.03341643, 0.01404109, 0.95155716, 0.17856896,
        0.26538646, 0.70535899, 0.62930288, 0.6920769 , 0.11986263,
        0.54098695, 0.11035619, 0.04511373, 0.15089325, 0.75170033,
        0.43856983, 0.33729393, 0.22314055, 0.25426049, 0.32882688,
        0.21180672, 0.87273313, 0.25730875, 0.84498919, 0.2111687 ,
        0.51118051, 0.93888725, 0.96275696, 0.63104651, 0.01160019,
        0.38008567, 0.07197381, 0.77267789, 0.32141824, 0.60414707,
        0.70436859, 0.7017014 , 0.46785649, 0.0652802 , 0.55827183,
        0.24791329, 0.00392165, 0.75562668, 0.25305559, 0.29004004,
        0.55409886, 0.9850196 , 0.00608005, 0.01878185, 0.02073481,
        0.93496573, 0.19179425, 0.14329057, 0.21470567, 0.94290747,
        0.58277105, 0.78739737, 0.83298911, 0.58

In [64]:
data1=pd.read_csv('weatherAUS.csv')

In [65]:
print(data1.head(1))

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   

   RainTomorrow  
0            No  

[1 rows x 23 columns]


In [67]:
data1['Combined']=data1.WindSpeed3pm +data1.WindSpeed9am

In [68]:
data1['Combined']

0         44.0
1         26.0
2         45.0
3         20.0
4         27.0
          ... 
145455    24.0
145456    22.0
145457    18.0
145458    20.0
145459    34.0
Name: Combined, Length: 145460, dtype: float64

In [69]:
data1

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
0            NaN           W           44.0          W  ...        22.0   
1            NaN         WNW           44.0        NNW  ...        25.0   
2            NaN         WSW           46.0          W  ...        30.0   
3            NaN          NE           24.0         SE  ...        16.0   
4            NaN           W           41.0        ENE  ...        33.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        24.0   
145456       NaN         NNW           22.0         SE  ...        21.0   
145457       NaN           N           37.0         SE  ...        24.0   
145458       NaN          SE           28.0        SSE  ...        24.0   
145459       NaN         NaN            NaN        ESE  ...        36.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0            1007.7       1007.1       8.0       NaN     16.9     21.8   
1            1010.6       1007.8       NaN       NaN     17.2     24.3   
2            1007.6       1008.7       NaN       2.0     21.0     23.2   
3            1017.6       1012.8       NaN       NaN     18.1     26.5   
4            1010.8       1006.0       7.0       8.0     17.8     29.7   
...             ...          ...       ...       ...      ...      ...   
145455       1024.6       1020.3       NaN       NaN     10.1     22.4   
145456       1023.5       1019.1       NaN       NaN     10.9     24.5   
145457       1021.0       1016.8       NaN       NaN     12.5     26.1   
145458       1019.4       1016.5       3.0       2.0     15.1     26.0   
145459       1020.2       1017.9       8.0       8.0     15.0     20.9   

        RainToday  RainTomorrow  Combined  
0              No            No      44.0  
1              No            No      26.0  
2              No            No      45.0  
3              No            No      20.0  
4              No            No      27.0  
...           ...           ...       ...  
145455         No            No      24.0  
145456         No            No      22.0  
145457         No            No      18.0  
145458         No            No      20.0  
145459         No           NaN      34.0  

[145460 rows x 24 columns]

In [72]:
data1=data1[data1.duplicated(subset=['WindSpeed3pm','WindSpeed9am'], keep="first")]

In [73]:
data1

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6       2008-12-07   Albury     14.3     25.0       0.0          NaN   
16      2008-12-17   Albury     14.1     20.9       0.0          NaN   
19      2008-12-20   Albury      9.8     25.6       0.0          NaN   
34      2009-01-04   Albury     12.3     34.6       0.0          NaN   
40      2009-01-10   Albury     17.0     30.8       0.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
6            NaN           W           50.0         SW  ...        19.0   
16           NaN         ENE           22.0        SSW  ...        82.0   
19           NaN         SSE           26.0         SE  ...        26.0   
34           NaN         WNW           37.0        SSE  ...        12.0   
40           NaN          NE           37.0        NNE  ...        24.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        24.0   
145456       NaN         NNW           22.0         SE  ...        21.0   
145457       NaN           N           37.0         SE  ...        24.0   
145458       NaN          SE           28.0        SSE  ...        24.0   
145459       NaN         NaN            NaN        ESE  ...        36.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6            1009.6       1008.2       1.0       NaN     18.1     24.6   
16           1012.2       1010.4       8.0       1.0     17.2     18.1   
19           1019.2       1017.1       NaN       NaN     15.8     23.2   
34           1015.1       1010.3       NaN       NaN     20.7     33.9   
40           1013.4       1008.1       NaN       NaN     20.2     29.3   
...             ...          ...       ...       ...      ...      ...   
145455       1024.6       1020.3       NaN       NaN     10.1     22.4   
145456       1023.5       1019.1       NaN       NaN     10.9     24.5   
145457       1021.0       1016.8       NaN       NaN     12.5     26.1   
145458       1019.4       1016.5       3.0       2.0     15.1     26.0   
145459       1020.2       1017.9       8.0       8.0     15.0     20.9   

        RainToday  RainTomorrow  Combined  
6              No            No      44.0  
16             No           Yes      20.0  
19             No            No      23.0  
34             No            No      23.0  
40             No            No      26.0  
...           ...           ...       ...  
145455         No            No      24.0  
145456         No            No      22.0  
145457         No            No      18.0  
145458         No            No      20.0  
145459         No           NaN      34.0  

[144442 rows x 24 columns]