In [1]:
import numpy as np
import pandas as pd

### creating an array and reshapping it

In [2]:
#create array 1D
array=np.arange(64)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [4]:
array=array.reshape(4,4,4)

In [5]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [10]:
array=array.astype('float64')
print(type(array))

<class 'numpy.ndarray'>


### Linespace

In [8]:
linespace=np.linspace(8,10,28)

In [9]:
linespace

array([ 8.        ,  8.07407407,  8.14814815,  8.22222222,  8.2962963 ,
        8.37037037,  8.44444444,  8.51851852,  8.59259259,  8.66666667,
        8.74074074,  8.81481481,  8.88888889,  8.96296296,  9.03703704,
        9.11111111,  9.18518519,  9.25925926,  9.33333333,  9.40740741,
        9.48148148,  9.55555556,  9.62962963,  9.7037037 ,  9.77777778,
        9.85185185,  9.92592593, 10.        ])

### Random array

In [13]:
random_arr= np.random.rand(1,100)

In [14]:
random_arr

array([[0.66946404, 0.45126012, 0.26642934, 0.21522734, 0.467464  ,
        0.59708748, 0.7390622 , 0.60415008, 0.60298274, 0.99932872,
        0.76608691, 0.96618491, 0.9347499 , 0.04172971, 0.17547567,
        0.51477646, 0.32576444, 0.7571657 , 0.95394771, 0.58251892,
        0.66051305, 0.72438074, 0.82706762, 0.36851036, 0.2887577 ,
        0.61885696, 0.60329301, 0.88065016, 0.81332155, 0.67717876,
        0.70258422, 0.69687006, 0.24529718, 0.90851255, 0.70656652,
        0.32511531, 0.73894532, 0.2523017 , 0.16654639, 0.77585457,
        0.17482955, 0.63731784, 0.25242974, 0.51673236, 0.32165242,
        0.85963319, 0.78528459, 0.86869707, 0.57641902, 0.51852803,
        0.05546365, 0.42532248, 0.01206669, 0.81478158, 0.59985903,
        0.74639753, 0.4507304 , 0.07978575, 0.08933947, 0.40468861,
        0.85283203, 0.74660399, 0.8743909 , 0.2204079 , 0.15652559,
        0.31388737, 0.76520175, 0.68822309, 0.03327463, 0.09750091,
        0.59501475, 0.16690249, 0.51672368, 0.45

### working on csv file using numpy

In [118]:
data1=pd.read_csv('weatherAUS.csv')
data1.dropna(inplace=True)

In [119]:
data1["WindSpeed3pm"]

6049      20.0
6050      19.0
6052      15.0
6053       6.0
6054      13.0
          ... 
142298    20.0
142299    11.0
142300    11.0
142301    17.0
142302     7.0
Name: WindSpeed3pm, Length: 56420, dtype: float64

In [120]:
data1["WindSpeed9am"]

6049       6.0
6050      19.0
6052      30.0
6053       6.0
6054      17.0
          ... 
142298     9.0
142299    13.0
142300    17.0
142301     9.0
142302    15.0
Name: WindSpeed9am, Length: 56420, dtype: float64

In [121]:
data1['combined']=data1["WindSpeed3pm"] +data1["WindSpeed9am"]

In [122]:
data1

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
6049    2009-01-01    Cobar     17.9     35.2       0.0         12.0   
6050    2009-01-02    Cobar     18.4     28.9       0.0         14.8   
6052    2009-01-04    Cobar     19.4     37.6       0.0         10.8   
6053    2009-01-05    Cobar     21.9     38.4       0.0         11.4   
6054    2009-01-06    Cobar     24.2     41.0       0.0         11.2   
...            ...      ...      ...      ...       ...          ...   
142298  2017-06-20   Darwin     19.3     33.4       0.0          6.0   
142299  2017-06-21   Darwin     21.2     32.6       0.0          7.6   
142300  2017-06-22   Darwin     20.7     32.8       0.0          5.6   
142301  2017-06-23   Darwin     19.5     31.8       0.0          6.2   
142302  2017-06-24   Darwin     20.2     31.7       0.0          5.6   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  \
6049        12.3         SSW           48.0        ENE  ...        13.0   
6050        13.0           S           37.0        SSE  ...         8.0   
6052        10.6         NNE           46.0        NNE  ...        22.0   
6053        12.2         WNW           31.0        WNW  ...        22.0   
6054         8.4         WNW           35.0         NW  ...        15.0   
...          ...         ...            ...        ...  ...         ...   
142298      11.0         ENE           35.0         SE  ...        32.0   
142299       8.6           E           37.0         SE  ...        28.0   
142300      11.0           E           33.0          E  ...        23.0   
142301      10.6         ESE           26.0         SE  ...        58.0   
142302      10.7         ENE           30.0        ENE  ...        32.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
6049         1006.3       1004.4       2.0       5.0     26.6     33.4   
6050         1012.9       1012.1       1.0       1.0     20.3     27.0   
6052         1012.3       1009.2       1.0       6.0     28.7     34.9   
6053         1012.7       1009.1       1.0       5.0     29.1     35.6   
6054         1010.7       1007.4       1.0       6.0     33.6     37.6   
...             ...          ...       ...       ...      ...      ...   
142298       1013.9       1010.5       0.0       1.0     24.5     32.3   
142299       1014.6       1011.2       7.0       0.0     24.8     32.0   
142300       1015.3       1011.8       0.0       0.0     24.8     32.1   
142301       1014.9       1010.7       1.0       1.0     24.8     29.2   
142302       1013.9       1009.7       6.0       5.0     25.4     31.0   

        RainToday  RainTomorrow  combined  
6049           No            No      26.0  
6050           No            No      38.0  
6052           No            No      45.0  
6053           No            No      12.0  
6054           No            No      30.0  
...           ...           ...       ...  
142298         No            No      29.0  
142299         No            No      24.0  
142300         No            No      28.0  
142301         No            No      26.0  
142302         No            No      22.0  

[56420 rows x 24 columns]

In [123]:
data1=data1[data1.duplicated(subset=['WindSpeed3pm','WindSpeed9am'], keep="first")]

In [125]:
data1.index

Int64Index([  6064,   6083,   6091,   6095,   6096,   6102,   6105,   6107,
              6111,   6113,
            ...
            142293, 142294, 142295, 142296, 142297, 142298, 142299, 142300,
            142301, 142302],
           dtype='int64', length=55649)